### PR TITLE
Implement task archiving.

### PR DESCRIPTION
**Pull request by cube2222**
Signed-off-by: Jakub Martin <kubam@spacelift.io>

Hey @raksul ! Couldn't find this in the library so here's a patch.

### CODE REVIEW

**Comment by w-haibara** [comment]
@cube2222 Sorry for the late reply.
I have a question about this PR. I could not find any description of this endpoint (`tasks/v1/archiveTasks/`). Could you please send me a link to the documentation?

**Comment by cube2222** [comment]
@w-haibara I don't think there is documentation for it.

I found it by using chrome devtools. It's what the UI uses to archive tasks (and there doesn't seem to be any other way to do it right now).

**Comment by w-haibara** [comment]
@cube2222 I see, thanks.
In my opinion, we should not support this endpoint now.
because this endpoint is not yet documented. Its specification may change quietly.

**Comment by cube2222** [comment]
@w-haibara Sure, I'm happy to keep using my fork for the archiving functionality.

**Pull request closed without merging**
