### PR TITLE
Added GetSeats and GetPlan (funcs, tests, and examples)

### PR DESCRIPTION
**Pull request by catdevman**
Fixed GetTeams test calling GetAuthorizedTeams

### CODE REVIEW

**Comment by catdevman** [comment]
@raksul Please review this it is a simple change and aside from one change only makes new structs and functions.  I need this for the ClickUp terraform provider I am making. Thank you!

**Review by a-thug — APPROVED** [review]
Thanks! 👍 

@w-haibara 
If all is well, could you merge this PR?

**Comment by w-haibara** [comment]
@catdevman san, thank you for your submission!
Could you please run go fmt?

**Comment by catdevman** [comment]
@w-haibara `go fmt` ran... not sure why but neovim wasn't auto formatting this project. Hope it all looks good now.

**Comment by w-haibara** [comment]
@catdevman Thanks! I'll merge it.

**Pull request merged**
